version: "3.8"

services:
  web:
    build: .
    container_name: binis-me
    restart: unless-stopped
    ports:
      - "4323:80"
    networks:
      - vps-network

networks:
  vps-network:
    external: true
